### ISSUE TITLE
Can't run analysis on binaries (nothing shown) 

### ISSUE THREAD

**Issue by kondah** [danieluhricek/LiSa#10]
Hello,

 First of all, thank you for your great work.
 I installed (using docker/docker-compose) Lisa and run it and everything were fine (just followed the tutorial on the wiki ).
 Lisa is running without a problem on Ubuntu 18.04 (i have access to the web interface) : 
![image](https://user-images.githubusercontent.com/7760108/76621278-3f94d780-64ec-11ea-80e3-09cdb424b1b9.png)

 When i upload a binary, everything is good for now and the binary is on the storage folder : 
![image](https://user-images.githubusercontent.com/7760108/76621315-53403e00-64ec-11ea-9b27-565dd8d96801.png)

 But when i go to the pending tasks, there's nothing shown on it (on finished and failed tabs also).
 When i checked the logs (after a while), i saw the following error :

> api_1       | [pid: 9|app: 0|req: 1/4] 172.42.0.1 () {40 vars in 589 bytes} [Fri Mar 13 12:36:51 2020] GET /api/tasks/failed => generated 3 bytes in 31 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
> rabbitmq_1  | 2020-03-13 12:36:53.444 [info] <0.1155.0> accepting AMQP connection <0.1155.0> (172.42.0.10:46460 -> 172.42.0.13:5672)
> api_1       | 2020-03-13 12:36:53 9:connection [DEBUG] - Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@c066dd39d2b3', 'copyright': 'Copyright (c) 2007-2020 Pivotal Software, Inc.', 'information': 'Licensed under the MPL 1.1. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 22.2.8', 'product': 'RabbitMQ', 'version': '3.8.3'}, mechanisms: [b'PLAIN', b'AMQPLAIN'], locales: ['en_US']
> api_1       | 2020-03-13 12:36:53 9:channel [DEBUG] - using channel_id: 1
> rabbitmq_1  | 2020-03-13 12:36:53.449 [info] <0.1155.0> connection <0.1155.0> (172.42.0.10:46460 -> 172.42.0.13:5672): user 'lisa' authenticated and granted access to vhost '/'
> api_1       | 2020-03-13 12:36:53 9:channel [DEBUG] - Channel open
> rabbitmq_1  | 2020-03-13 12:36:53.472 [info] <0.1171.0> accepting AMQP connection <0.1171.0> (172.42.0.10:46462 -> 172.42.0.13:5672)
> api_1       | 2020-03-13 12:36:53 9:connection [DEBUG] - Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@c066dd39d2b3', 'copyright': 'Copyright (c) 2007-2020 Pivotal Software, Inc.', 'information': 'Licensed under the MPL 1.1. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 22.2.8', 'product': 'RabbitMQ', 'version': '3.8.3'}, mechanisms: [b'PLAIN', b'AMQPLAIN'], locales: ['en_US']
> rabbitmq_1  | 2020-03-13 12:36:53.479 [info] <0.1171.0> connection <0.1171.0> (172.42.0.10:46462 -> 172.42.0.13:5672): user 'lisa' authenticated and granted access to vhost '/'
> api_1       | 2020-03-13 12:36:53 9:channel [DEBUG] - using channel_id: 1
> api_1       | 2020-03-13 12:36:53 9:channel [DEBUG] - Channel open
> api_1       | [pid: 9|app: 0|req: 2/5] 172.42.0.1 () {40 vars in 592 bytes} [Fri Mar 13 12:36:53 2020] GET /api/tasks/pending => generated 5 bytes in 1098 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
> nginx_1     | 172.42.0.1 - - [13/Mar/2020:12:36:54 +0000] "GET /api/tasks/pending HTTP/1.1" 200 5 "http://localhost:4242/pending" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" "-"
> rabbitmq_1  | 2020-03-13 12:37:20.558 [error] <0.950.0> closing AMQP connection <0.950.0> (172.42.0.10:46426 -> 172.42.0.13:5672):
> rabbitmq_1  | missed heartbeats from client, timeout: 60s
> rabbitmq_1  | 2020-03-13 12:37:53.270 [error] <0.996.0> closing AMQP connection <0.996.0> (172.42.0.10:46434 -> 172.42.0.13:5672):
> rabbitmq_1  | missed heartbeats from client, timeout: 60s
> rabbitmq_1  | 2020-03-13 12:37:53.300 [error] <0.1013.0> closing AMQP connection <0.1013.0> (172.42.0.10:46436 -> 172.42.0.13:5672):
> rabbitmq_1  | missed heartbeats from client, timeout: 60s
> rabbitmq_1  | 2020-03-13 12:39:53.452 [error] <0.1155.0> closing AMQP connection <0.1155.0> (172.42.0.10:46460 -> 172.42.0.13:5672):
> rabbitmq_1  | missed heartbeats from client, timeout: 60s
> rabbitmq_1  | 2020-03-13 12:39:53.482 [error] <0.1171.0> closing AMQP connection <0.1171.0> (172.42.0.10:46462 -> 172.42.0.13:5672):
> rabbitmq_1  | missed heartbeats from client, timeout: 60s
> api_1       | [pid: 12|app: 0|req: 3/6] 172.42.0.1 () {40 vars in 587 bytes} [Fri Mar 13 12:40:26 2020] GET /api/tasks/finished => generated 3 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
> nginx_1     | 172.42.0.1 - - [13/Mar/2020:12:40:26 +0000] "GET /api/tasks/finished HTTP/1.1" 200 3 "http://localhost:4242/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" "-"
> api_1       | [pid: 12|app: 0|req: 4/7] 172.42.0.1 () {40 vars in 589 bytes} [Fri Mar 13 12:41:52 2020] GET /api/tasks/failed => generated 3 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
> nginx_1     | 172.42.0.1 - - [13/Mar/2020:12:41:52 +0000] "GET /api/tasks/failed HTTP/1.1" 200 3 "http://localhost:4242/failed" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" "-"
> api_1       | 2020-03-13 12:41:53 13:app [ERROR] - Exception on /api/tasks/pending [GET]
> api_1       | Traceback (most recent call last):
> api_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> api_1       |     response = self.full_dispatch_request()
> api_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> api_1       |     rv = self.handle_user_exception(e)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
> api_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
> api_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> api_1       |     reraise(exc_type, exc_value, tb)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> api_1       |     raise value
> api_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> api_1       |     rv = self.dispatch_request()
> api_1       |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> api_1       |     return self.view_functions[rule.endpoint](**req.view_args)
> api_1       |   File "./lisa/web_api/routes.py", line 116, in list_pending_tasks
> api_1       |     pending = i.reserved()
> api_1       |   File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 125, in reserved
> api_1       |     return self._request('reserved')
> api_1       |   File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 106, in _request
> api_1       |     pattern=self.pattern, matcher=self.matcher,
> api_1       |   File "/usr/local/lib/python3.6/site-packages/celery/app/control.py", line 477, in broadcast
> api_1       |     limit, callback, channel=channel,
> api_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 346, in _broadcast
> api_1       |     matcher=matcher)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/pidbox.py", line 302, in _publish
> api_1       |     maybe_declare(self.reply_queue(channel))
> api_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 121, in maybe_declare
> api_1       |     return _maybe_declare(entity, channel)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/common.py", line 161, in _maybe_declare
> api_1       |     entity.declare(channel=channel)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/entity.py", line 608, in declare
> api_1       |     self._create_exchange(nowait=nowait, channel=channel)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/entity.py", line 615, in _create_exchange
> api_1       |     self.exchange.declare(nowait=nowait, channel=channel)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/entity.py", line 186, in declare
> api_1       |     nowait=nowait, passive=passive,
> api_1       |   File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 614, in exchange_declare
> api_1       |     wait=None if nowait else spec.Exchange.DeclareOk,
> api_1       |   File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
> api_1       |     conn.frame_writer(1, self.channel_id, sig, args, content)
> api_1       |   File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 172, in write_frame
> api_1       |     write(view[:offset])
> api_1       |   File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 284, in write
> api_1       |     self._write(s)
> api_1       | ConnectionResetError: [Errno 104] Connection reset by peer
> api_1       | [pid: 13|app: 0|req: 2/8] 172.42.0.1 () {40 vars in 592 bytes} [Fri Mar 13 12:41:53 2020]
> mariadb_1   | 2020-03-13 12:46:51 9 [Warning] Aborted connection 9 to db: 'lisadb' user: 'lisa' host: '172.42.0.10' (Got timeout reading communication packets)

And also after a while "nothing" is shown .
Can you help me fix this issue ?
 Thanks

**Comment by jrespeto** [comment]
you still need help with this?

**Comment by danielpoliakov** [comment]
Hi, should be already fixed by past commits, feel free to reopen the issue if you still encounter any problems.
