### ISSUE TITLE
Submit binary took long time

### ISSUE THREAD

**Issue by fareedfauzi** [danieluhricek/LiSa#14]
Submit binary took long time (might forever)

![image](https://user-images.githubusercontent.com/56353946/97067763-56a7b600-15f3-11eb-97ae-bc88a53b8c8d.png)

Anyone had faced this situation?

**Comment by gallypette** [comment]
Same issue here.
Submitting jobs through the API seems to work though:
`curl -X POST -F 'file=@./myfile' http://localhost:4242/api/tasks/create/file`
edit: I restarted the whole thingy and now it works oO

**Comment by danielpoliakov** [comment]
Hi, should be fixed by 3e57bc9 - feel free to reopen the issue if the problem persists (and provide log if possible).
