### ISSUE TITLE
MaxMind GeoLite databases links can't be accessiable

### ISSUE THREAD

**Issue by nghiango1** [danieluhricek/LiSa#5]
Hi,

So when I try to install Lisa, the docker build in service 'worker' contain these wget links
```
    && echo "Downloading MaxMind GeoLite databases ..." \
    && wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz -q -O - | tar xz -C data/geolite2databases \
    && wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz -q -O - | tar xz -C data/geolite2databases \
```
which are now not accessible anymore and require a registered account to download in MaxMind new policy. This needs a little bit of fix and things will work just smooth as before.

**Comment by firmianay** [comment]
Just need to add an argument 'YOUR_LICENSE_KEY' in worker's dockerfile
```
# Database URL
https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=YOUR_LICENSE_KEY&suffix=tar.gz
```

**Comment by danielpoliakov** [comment]
Hi, thanks for mentioning MaxMind policy. API key is now configurable in docker-compose.yml - [commit](https://github.com/danieluhricek/LiSa/commit/40b94fa809a637e9170d984512d1ed4e4a83020b). If no API key is provided, network analysis will just ommit quering geo info.
